openapi: 3.0.3
info:
  title: Sample Products API
  version: 1.0.0
paths:
  /products:
    get:
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: components/product.yaml
              examples:
                GET_PRODUCT:
                  value:
                    id: "1"
                    name: "XYZ Product"
                    inventory: 100

