get:
  responses:
    "200":
      description: successful operation
      content:
        application/json:
          schema:
            $ref: ../components/product.yaml
          examples:
            GET_PRODUCT:
              value:
                id: "1"
                name: "XYZ Product"
                inventory: 100
